import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout-ui/Header";
import PageTransitions from "@/components/layout-ui/PageTransitions";
import StairEffect from "@/components/layout-ui/StairEffect";
import CursorProvider from "@/context/CursorContext";
import CustomCursor from "@/components/custom-ui/CustomCursor";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CursorProvider>
        <body className={jetBrainsMono.variable}>
          <StairEffect />
          <PageTransitions>
            <Header />
            {children}
          </PageTransitions>
          <CustomCursor/>
        </body>
      </CursorProvider>
    </html>
  );
}
